# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1406, 934)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(10, 80, 221, 381))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.treeWidget.setFont(font)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        icon = QtGui.QIcon.fromTheme("a")
        self.treeWidget.headerItem().setIcon(0, icon)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 30, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(250, 80, 201, 391))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("信息")
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 550, 441, 301))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(26)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 480, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 480, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(500, 210, 861, 471))
        self.label_1.setObjectName("label_1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.treeWidget.expandAll)
        self.pushButton_2.clicked.connect(self.treeWidget.reset)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "信息查询"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "楼号"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "#1"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "1单元"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "A11"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "A12"))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("MainWindow", "A13"))
        self.treeWidget.topLevelItem(0).child(0).child(3).setText(0, _translate("MainWindow", "A14"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "2单元"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "A21"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "A22"))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(0, _translate("MainWindow", "A23"))
        self.treeWidget.topLevelItem(0).child(1).child(3).setText(0, _translate("MainWindow", "A24"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "3单元"))
        self.treeWidget.topLevelItem(0).child(2).child(0).setText(0, _translate("MainWindow", "A31"))
        self.treeWidget.topLevelItem(0).child(2).child(1).setText(0, _translate("MainWindow", "A32"))
        self.treeWidget.topLevelItem(0).child(2).child(2).setText(0, _translate("MainWindow", "A33"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "4单元"))
        self.treeWidget.topLevelItem(0).child(3).child(0).setText(0, _translate("MainWindow", "A41"))
        self.treeWidget.topLevelItem(0).child(3).child(1).setText(0, _translate("MainWindow", "A42"))
        self.treeWidget.topLevelItem(0).child(3).child(2).setText(0, _translate("MainWindow", "A43"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "#2"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "1单元"))
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, _translate("MainWindow", "B11"))
        self.treeWidget.topLevelItem(1).child(0).child(1).setText(0, _translate("MainWindow", "B12"))
        self.treeWidget.topLevelItem(1).child(0).child(2).setText(0, _translate("MainWindow", "B13"))
        self.treeWidget.topLevelItem(1).child(0).child(3).setText(0, _translate("MainWindow", "B14"))
        self.treeWidget.topLevelItem(1).child(0).child(4).setText(0, _translate("MainWindow", "B15"))
        self.treeWidget.topLevelItem(1).child(0).child(5).setText(0, _translate("MainWindow", "B16"))
        self.treeWidget.topLevelItem(1).child(0).child(6).setText(0, _translate("MainWindow", "B17"))
        self.treeWidget.topLevelItem(1).child(0).child(7).setText(0, _translate("MainWindow", "B18"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "2单元"))
        self.treeWidget.topLevelItem(1).child(1).child(0).setText(0, _translate("MainWindow", "B21"))
        self.treeWidget.topLevelItem(1).child(1).child(1).setText(0, _translate("MainWindow", "B22"))
        self.treeWidget.topLevelItem(1).child(1).child(2).setText(0, _translate("MainWindow", "B23"))
        self.treeWidget.topLevelItem(1).child(1).child(3).setText(0, _translate("MainWindow", "B24"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "3单元"))
        self.treeWidget.topLevelItem(1).child(2).child(0).setText(0, _translate("MainWindow", "B31"))
        self.treeWidget.topLevelItem(1).child(2).child(1).setText(0, _translate("MainWindow", "B32"))
        self.treeWidget.topLevelItem(1).child(2).child(2).setText(0, _translate("MainWindow", "B33"))
        self.treeWidget.topLevelItem(1).child(2).child(3).setText(0, _translate("MainWindow", "B34"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "4单元"))
        self.treeWidget.topLevelItem(1).child(3).child(0).setText(0, _translate("MainWindow", "B41"))
        self.treeWidget.topLevelItem(1).child(3).child(1).setText(0, _translate("MainWindow", "B42"))
        self.treeWidget.topLevelItem(1).child(3).child(2).setText(0, _translate("MainWindow", "B43"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "#3"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "1单元"))
        self.treeWidget.topLevelItem(2).child(0).child(0).setText(0, _translate("MainWindow", "C11"))
        self.treeWidget.topLevelItem(2).child(0).child(1).setText(0, _translate("MainWindow", "C12"))
        self.treeWidget.topLevelItem(2).child(0).child(2).setText(0, _translate("MainWindow", "C13"))
        self.treeWidget.topLevelItem(2).child(0).child(3).setText(0, _translate("MainWindow", "C14"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "2单元"))
        self.treeWidget.topLevelItem(2).child(1).child(0).setText(0, _translate("MainWindow", "C21"))
        self.treeWidget.topLevelItem(2).child(1).child(1).setText(0, _translate("MainWindow", "C22"))
        self.treeWidget.topLevelItem(2).child(1).child(2).setText(0, _translate("MainWindow", "C23"))
        self.treeWidget.topLevelItem(2).child(1).child(3).setText(0, _translate("MainWindow", "C24"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "3单元"))
        self.treeWidget.topLevelItem(2).child(2).child(0).setText(0, _translate("MainWindow", "C31"))
        self.treeWidget.topLevelItem(2).child(2).child(1).setText(0, _translate("MainWindow", "C32"))
        self.treeWidget.topLevelItem(2).child(2).child(2).setText(0, _translate("MainWindow", "C33"))
        self.treeWidget.topLevelItem(2).child(2).child(3).setText(0, _translate("MainWindow", "C34"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "4单元"))
        self.treeWidget.topLevelItem(2).child(3).child(0).setText(0, _translate("MainWindow", "C41"))
        self.treeWidget.topLevelItem(2).child(3).child(1).setText(0, _translate("MainWindow", "C42"))
        self.treeWidget.topLevelItem(2).child(3).child(2).setText(0, _translate("MainWindow", "C43"))
        self.treeWidget.topLevelItem(2).child(3).child(3).setText(0, _translate("MainWindow", "C44"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "#4"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "1单元"))
        self.treeWidget.topLevelItem(3).child(0).child(0).setText(0, _translate("MainWindow", "D11"))
        self.treeWidget.topLevelItem(3).child(0).child(1).setText(0, _translate("MainWindow", "D12"))
        self.treeWidget.topLevelItem(3).child(0).child(2).setText(0, _translate("MainWindow", "D13"))
        self.treeWidget.topLevelItem(3).child(0).child(3).setText(0, _translate("MainWindow", "D14"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "2单元"))
        self.treeWidget.topLevelItem(3).child(1).child(0).setText(0, _translate("MainWindow", "D21"))
        self.treeWidget.topLevelItem(3).child(1).child(1).setText(0, _translate("MainWindow", "D22"))
        self.treeWidget.topLevelItem(3).child(1).child(2).setText(0, _translate("MainWindow", "D23"))
        self.treeWidget.topLevelItem(3).child(1).child(3).setText(0, _translate("MainWindow", "D24"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "3单元"))
        self.treeWidget.topLevelItem(3).child(2).child(0).setText(0, _translate("MainWindow", "D31"))
        self.treeWidget.topLevelItem(3).child(2).child(1).setText(0, _translate("MainWindow", "D32"))
        self.treeWidget.topLevelItem(3).child(2).child(2).setText(0, _translate("MainWindow", "D33"))
        self.treeWidget.topLevelItem(3).child(2).child(3).setText(0, _translate("MainWindow", "D34"))
        self.treeWidget.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "4单元"))
        self.treeWidget.topLevelItem(3).child(3).child(0).setText(0, _translate("MainWindow", "D41"))
        self.treeWidget.topLevelItem(3).child(3).child(1).setText(0, _translate("MainWindow", "D42"))
        self.treeWidget.topLevelItem(3).child(3).child(2).setText(0, _translate("MainWindow", "D43"))
        self.treeWidget.topLevelItem(3).child(3).child(3).setText(0, _translate("MainWindow", "D44"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "信息"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "信息"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "信息"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:26pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt;\">这里是门牌号信息</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "展开"))
        self.pushButton_2.setText(_translate("MainWindow", "初始化"))
        self.label_1.setText(_translate("MainWindow", "TextLabel"))
